config/routes.rb
Rails.application.routes.draw do

  #mount_ember_app :editor, to: "/editor"

  resources :referrals do
    collection do
      get :accept
    end
  end

  namespace :api do
    resources :user_state, only: :show
  end

  devise_for :users, :controllers => {:sessions => "users/sessions", :passwords => "users/passwords"}

  devise_scope :user do
    post "/users/find_email", to: "users/sessions#find_email", as: :find_email

    get "/users/forgot_email", to: "users/forgot_emails#new", as: :new_forgot_email
    post "/users/forgot_email", to: "users/forgot_emails#create", as: :forgot_email
  end

  post "/users/:user_id/update_exit_intent", to: "user_campaign#update_exit_intent", as: :update_user_exit_intent
  post "/users/:user_id/update_upgrade_suggest", to: "user_campaign#update_upgrade_suggest", as: :update_user_upgrade_suggest

  get "/auth/:action/callback", :to => "users/omniauth_callbacks", :constraints => { :action => /google_oauth2/ }

  get "profile", :to => "user#edit", :as => :profile
  resource :user, :controller => :user, :only => [:update, :destroy, :create]
  get "user/new/:invite_token", :to => "user#new", :as => :invite_user

  resources :sites do
    member do
      put :downgrade
    end

    get "team"

    post :track_selected_goal, to: "tracking#track_selected_goal"

    resource :wordpress_plugin, :controller => :wordpress_plugin

    put "site_elements/:id/toggle_paused", to: "site_elements#toggle_paused", as: :site_element_toggle_paused
    resources :site_elements
    get "site_elements/:id/edit/*path", to: "site_elements#edit"
    get "site_elements/new/*path", to: "site_elements#new"

    resources :image_uploads, only: [:create]

    resources :rules do
      resources :conditions
    end

    resources :identities
    resources :contact_lists
    resources :targeted_segments

    resources :site_memberships do
      collection do
        post "invite"
      end
    end
  end

  namespace :modals do
    get :registration
  end

  resources :payment_methods, only: [:index, :create, :update]
  resources :bills, only: :show

  get "continue_create_site", :to => "sites#create", :as => :continue_create_site
  get "sites/:id/install", :to => "sites#install", :as => :site_install
  get "sites/:id/improve", :to => "sites#improve", :as => :site_improve
  get "sites/:id/preview_script", :to => "sites#preview_script", :as => :preview_script
  get "sites/:id/script", :to => "sites#script", :as => :script
  get "sites/:id/chart_data", to: "sites#chart_data", as: :chart_data
  get "sites/:id/whats_new", :to => "sites#whats_new", :as => :whats_new

  get "/auth/:provider/callback", :to => "identities#create"

  resources :contact_submissions, only: [:create]
  get "/contact", :to => "contact_submissions#new", :as => :new_contact_submission

  %w(email_developer generic_message).each do |sub|
    post "/contact_submissions/#{sub}", :to => "contact_submissions##{sub}", :as => "#{sub}_contact_submission"
  end

  get "/admin", :to => "admin/users#index", :as => :admin
  namespace :admin do
    post "users/:id/impersonate", :to => "users#impersonate", :as => :impersonate_user
    delete "users/unimpersonate", :to => "users#unimpersonate", :as => :unimpersonate_user

    resources :admins, only: :index do
      member do
        put :unlock
      end
    end

    resources :payment_method_details, only: [] do
      put 'remove_cc_info'
    end

    resources :users, :only => [:index, :show, :destroy] do
      resources :sites, :only => [:update] do
        member do
          post :regenerate
        end

        resources :contact_lists, :only => [:index]
      end

      resources :bills, :only => [:show] do
        put 'void'
        put 'refund'
      end
    end

    get "lockdown/:email/:key/:timestamp", :to => "access#lockdown", :constraints => {:email => /[^\/]+/}, :as => :lockdown
    get "validate_access_token/:email/:key/:timestamp", :to => "access#validate_access_token", :constraints => {:email => /[^\/]+/}, :as => :validate_access_token
    get "logout", :to => "access#logout_admin", :as => :logout
    get "reset_password", :to => "access#reset_password"
    post "reset_password", :to => "access#do_reset_password"
    get "access", :to => "access#step1", :as => :access
    post "access/authenticate", :to => "access#process_step2", :as => :authenticate
    post "access", :to => "access#process_step1"
    get "locked", :to => "access#locked", :as => :locked
  end

  post "/track/current_person/did/:event" => "tracking#track_current_person"
  post "/track/:type/:id/did/:event" => "tracking#track"
  get "/pixel.gif" => "tracking#pixel", :as => :tracking_pixel

  get "/install" => "sites#install_redirect"

  get '/use-cases' => 'pages#use_cases'
  get '/amazon' => 'pages#use_cases'
  get '/terms-of-use' => 'pages#terms_of_use'
  get '/privacy-policy' => 'pages#privacy_policy'
  get '/migrate-faq' => 'pages#migrate_faq'
  get '/logged_out' => 'pages#logout_confirmation', as: :logout_confirmation

  get "/heartbeat" => "heartbeat#index"
  get "/login", to: redirect("/users/sign_in")
  get "/signup", to: redirect("/")

  get "/user_migration", to: "user_migration#new", as: :new_user_migration
  get "/upgrade", to: "user_migration#upgrade", as: :user_migration_landing
  post "/start_migration", to: "user_migration#start", as: :start_user_migration
  post "/user_migration", to: "user_migration#create", as: :user_migration

  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  get "/proxy/:scheme/*url", to: "proxy#proxy" if Rails.env.development?

  get "/email-signup", to: "welcome#email_quickstart"
  root "welcome#index"
end

app/controllers/admin/access_controller.rb
class Admin::AccessController < ApplicationController
  layout "admin"

  before_action :require_admin, :only => [:reset_password, :do_reset_password, :logout_admin]
  before_action :redirect_admin, :only => :step1

  def do_reset_password
    if current_admin.password_hashed != current_admin.encrypt_password(params[:existing_password])
      @error = "Your existing password is incorrect"
    elsif params[:new_password] != params[:new_password_again]
      @error = "Your new passwords did not match each other"
    elsif !params[:new_password] or params[:new_password].length < Admin::MIN_PASSWORD_LENGTH
      @error = "New password must be at least #{Admin::MIN_PASSWORD_LENGTH} chars"
    elsif params[:new_password] == params[:existing_password]
      @error = "New password must be different than existing password."
    end

    if @error
      flash.now[:error] = @error
      render :reset_password
    else
      current_admin.reset_password!(params[:new_password])
      redirect_to admin_path
    end
  end

  def logout_admin
    current_admin.logout!
    session.delete(:admin_token)
    flash[:success] = "You are now logged out."

    redirect_to admin_access_path
  end

  def process_step1
    return redirect_to(admin_access_path) unless email = params[:login_email]

    session[:admin_access_email] = email

    unless Admin.any_validated_access_token?(access_token) || verify_recaptcha
      return redirect_to(admin_access_path)
    end

    Admin.record_login_attempt(email, remote_ip, user_agent, access_cookie)

    if @admin = Admin.where(:email => email).first
      process_login(@admin)
    else
      # Always render step2 - this way attackers don't know if the login
      # email is valid or not
      render(:step2)
    end
  end

  def process_step2
    return redirect_to(admin_access_path) unless email = session[:admin_access_email]

    @admin = Admin.where(:email => email).first

    return render(:step2) unless @admin
    return redirect_to(admin_locked_path) if @admin.locked?
    return render(:validate_access_token) unless @admin.has_validated_access_token?(access_token)

    if @admin.validate_login(access_token, params[:admin_password], params[:otp])
      # Successful login
      session[:admin_token] = @admin.session_token
      redirect_to admin_path
    else
      flash.now[:error] = "Invalid OTP or password or too many attempts"
      render :step2
    end
  end

  def lockdown
    if Admin.validate_lockdown(params[:email], params[:key], params[:timestamp].to_i)
      Admin.lockdown!
      render :text => "Admins have been successfully locked down"
    else
      render :text => "Admins could not be locked down"
    end
  end

  def validate_access_token
    return redirect_to(admin_access_path) unless email = params[:email]

    admin = Admin.where(:email => email).first

    return render(:step2) unless admin
    return redirect_to(admin_locked_path) if admin.locked?

    if admin.validate_access_token(access_token, params[:key], params[:timestamp].to_i)
      process_login(admin)
    else
      render :validate_access_token
    end
  end

  private

  def process_login(admin)
    return redirect_to(admin_locked_path) if admin.locked?

    # If they have validated the access token then we
    # can render step 2
    unless admin.has_validated_access_token?(access_token)
      admin.send_validate_access_token_email!(access_token)
      return render(:validate_access_token)
    end

    return redirect_to(admin_locked_path) if admin.locked?

    @admin = admin
    render(:step2)
  end

  def redirect_admin
    return redirect_to(admin_path) if current_admin
  end
end

app/helpers/admin/access_helper.rb
module Admin::AccessHelper
  require 'rqrcode'

  def qr_code_from(otp)
    @qr ||= RQRCode::QRCode.new(otp) if otp.present?
  end
end

app/views/admin/access/_authentication_code.html.slim
- @qr = qr_code_from(@otp)
- if @qr
  .barcode-wrapper
    .barcode-section
      = "Scan this code using Google Authenticator on your phone"
      table
        - @qr.modules.each_index do |x|
          tr
            - @qr.modules.each_index do |y|
              - if @qr.dark?(x,y)
                td.black
              - else
                td.white

app/views/admin/access/_qr_code.html.slim
- @qr = qr_code_from(generated_otp)
- if @qr
  .barcode-wrapper
    .barcode-section
      = "Scan this code using Google Authenticator on your phone"
      table
        - @qr.modules.each_index do |x|
          tr
            - @qr.modules.each_index do |y|
              - if @qr.dark?(x,y)
                td.black
              - else
                td.white

app/views/admin/access/locked.html.slim
h2 Locked
p This account has been locked. It must be manually unlocked.

app/views/admin/access/reset_password.html.slim
div.row
  div.col-md-4
  div.col-md-4
    h1 You Need to Change Your Password

    = simple_form_for :reset_password, {:url => "/admin/reset_password"} do |f|
      = f.input :existing_password, :input_html => {:name => :existing_password}
      = f.input :new_password, :input_html => {:name => :new_password}
      = f.input :new_password_again, :input_html => {:name => :new_password_again}
      = f.button :submit, "Continue", :class => "btn btn-primary"

  div.col-md-4

app/views/admin/access/step1.html.slim
div.row
  div.col-md-4
  div.col-md-4
    h1 Admin

    = simple_form_for :new_admin, {:url => "/admin/access"} do |f|
      = f.input :login_email, :label => "Email address", :input_html => {:name => :login_email}

      - unless Admin.any_validated_access_token?(access_token)
        div= recaptcha_tags
        p
          br
          small If you have Disconnect extension for Chrome or Firefox, please disable it and reload to log in.

      = f.button :submit, "Continue", :class => "btn btn-primary"

  div.col-md-4

app/views/admin/access/step2.html.slim
div.row
  div.col-md-4
  div.col-md-4
    h1 Enter Password

    = simple_form_for :admin_authenticate, {:url => admin_authenticate_path} do |f|
      - if @admin.present? && @admin.needs_otp_code?
        = render partial: "qr_code", locals: { generated_otp: @admin.generate_new_otp! }

      = f.input :otp, :input_html => {:name => :otp}
      = f.input :password, :input_html => {:name => :admin_password}
      = f.button :submit, "Continue", :class => "btn btn-primary"

  div.col-md-4

app/views/admin/access/validate_access_token.html.slim
h1 Please check your email
p This is an unrecognized computer. You will be receiving an email with a confirmation link that this is really you shortly.