config/routes.rb
Rails.application.routes.draw do

  #mount_ember_app :editor, to: "/editor"

  resources :referrals do
    collection do
      get :accept
    end
  end

  namespace :api do
    resources :user_state, only: :show
  end

  devise_for :users, :controllers => {:sessions => "users/sessions", :passwords => "users/passwords"}

  devise_scope :user do
    post "/users/find_email", to: "users/sessions#find_email", as: :find_email

    get "/users/forgot_email", to: "users/forgot_emails#new", as: :new_forgot_email
    post "/users/forgot_email", to: "users/forgot_emails#create", as: :forgot_email
  end

  post "/users/:user_id/update_exit_intent", to: "user_campaign#update_exit_intent", as: :update_user_exit_intent
  post "/users/:user_id/update_upgrade_suggest", to: "user_campaign#update_upgrade_suggest", as: :update_user_upgrade_suggest

  get "/auth/:action/callback", :to => "users/omniauth_callbacks", :constraints => { :action => /google_oauth2/ }

  get "profile", :to => "user#edit", :as => :profile
  resource :user, :controller => :user, :only => [:update, :destroy, :create]
  get "user/new/:invite_token", :to => "user#new", :as => :invite_user

  resources :sites do
    member do
      put :downgrade
    end

    get "team"

    post :track_selected_goal, to: "tracking#track_selected_goal"

    resource :wordpress_plugin, :controller => :wordpress_plugin

    put "site_elements/:id/toggle_paused", to: "site_elements#toggle_paused", as: :site_element_toggle_paused
    resources :site_elements
    get "site_elements/:id/edit/*path", to: "site_elements#edit"
    get "site_elements/new/*path", to: "site_elements#new"

    resources :image_uploads, only: [:create]

    resources :rules do
      resources :conditions
    end

    resources :identities
    resources :contact_lists
    resources :targeted_segments

    resources :site_memberships do
      collection do
        post "invite"
      end
    end
  end

  namespace :modals do
    get :registration
  end

  resources :payment_methods, only: [:index, :create, :update]
  resources :bills, only: :show

  get "continue_create_site", :to => "sites#create", :as => :continue_create_site
  get "sites/:id/install", :to => "sites#install", :as => :site_install
  get "sites/:id/improve", :to => "sites#improve", :as => :site_improve
  get "sites/:id/preview_script", :to => "sites#preview_script", :as => :preview_script
  get "sites/:id/script", :to => "sites#script", :as => :script
  get "sites/:id/chart_data", to: "sites#chart_data", as: :chart_data
  get "sites/:id/whats_new", :to => "sites#whats_new", :as => :whats_new

  get "/auth/:provider/callback", :to => "identities#create"

  resources :contact_submissions, only: [:create]
  get "/contact", :to => "contact_submissions#new", :as => :new_contact_submission

  %w(email_developer generic_message).each do |sub|
    post "/contact_submissions/#{sub}", :to => "contact_submissions##{sub}", :as => "#{sub}_contact_submission"
  end

  get "/admin", :to => "admin/users#index", :as => :admin
  namespace :admin do
    post "users/:id/impersonate", :to => "users#impersonate", :as => :impersonate_user
    delete "users/unimpersonate", :to => "users#unimpersonate", :as => :unimpersonate_user

    resources :admins, only: :index do
      member do
        put :unlock
      end
    end

    resources :payment_method_details, only: [] do
      put 'remove_cc_info'
    end

    resources :users, :only => [:index, :show, :destroy] do
      resources :sites, :only => [:update] do
        member do
          post :regenerate
        end

        resources :contact_lists, :only => [:index]
      end

      resources :bills, :only => [:show] do
        put 'void'
        put 'refund'
      end
    end

    get "lockdown/:email/:key/:timestamp", :to => "access#lockdown", :constraints => {:email => /[^\/]+/}, :as => :lockdown
    get "validate_access_token/:email/:key/:timestamp", :to => "access#validate_access_token", :constraints => {:email => /[^\/]+/}, :as => :validate_access_token
    get "logout", :to => "access#logout_admin", :as => :logout
    get "reset_password", :to => "access#reset_password"
    post "reset_password", :to => "access#do_reset_password"
    get "access", :to => "access#step1", :as => :access
    post "access/authenticate", :to => "access#process_step2", :as => :authenticate
    post "access", :to => "access#process_step1"
    get "locked", :to => "access#locked", :as => :locked
  end

  post "/track/current_person/did/:event" => "tracking#track_current_person"
  post "/track/:type/:id/did/:event" => "tracking#track"
  get "/pixel.gif" => "tracking#pixel", :as => :tracking_pixel

  get "/install" => "sites#install_redirect"

  get '/use-cases' => 'pages#use_cases'
  get '/amazon' => 'pages#use_cases'
  get '/terms-of-use' => 'pages#terms_of_use'
  get '/privacy-policy' => 'pages#privacy_policy'
  get '/migrate-faq' => 'pages#migrate_faq'
  get '/logged_out' => 'pages#logout_confirmation', as: :logout_confirmation

  get "/heartbeat" => "heartbeat#index"
  get "/login", to: redirect("/users/sign_in")
  get "/signup", to: redirect("/")

  get "/user_migration", to: "user_migration#new", as: :new_user_migration
  get "/upgrade", to: "user_migration#upgrade", as: :user_migration_landing
  post "/start_migration", to: "user_migration#start", as: :start_user_migration
  post "/user_migration", to: "user_migration#create", as: :user_migration

  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  get "/proxy/:scheme/*url", to: "proxy#proxy" if Rails.env.development?

  get "/email-signup", to: "welcome#email_quickstart"
  root "welcome#index"
end

app/models/site_elements/modal.rb
class Modal < SiteElement
  def placement
    read_attribute(:placement) || "middle"
  end
end

app/controllers/modals_controller.rb
class ModalsController < ApplicationController
  layout false

  def registration; end
end

app/helpers/modal_helper.rb
module ModalHelper
  def upgrade_modal_AB_class
    'upgrade-account-modal'
  end
end

app/views/shared/modals/_account_prompt.html.slim
script id='account-prompt-modal-template' type='text/x-handlebars-template'
  .modal-wrapper
    = form_for current_user, html: {class: "modal-block"} do |f|
      header
        h5 Wait! You're almost done!

      .account-prompt-modal
        .flash-block
          i.icon-close

        p Before you install your Hello Bar, please enter your email and password below. This will allow you to return and make changes later.

        .thirds-wrapper
          .thirds
            label Email
            input type='email' placeholder='name@email.com' name="user[email]" id="user_email"

          .thirds
            label Password
            input type='password' placeholder='••••••' name="user[password]" id="user_password"

          .thirds
            label Timezone
            .select-wrapper
              = select 'user', 'timezone', time_zone_options

        = hidden_field_tag :detect_timezone

      footer
        input type="submit" class="button" value="Save Account"

script id='alternate-account-prompt-modal-template' type='text/x-handlebars-template'
  .modal-wrapper
    = form_for current_user, html: {class: "modal-block"} do |f|
      header class="{{headerClass}}"
        h5 
          i.icon-alert
          | To install Hello Bar on {{siteURL}} you must 
          strong create a free account 
          | below

      .account-prompt-modal
        .flash-block
          i.icon-close

        .thirds-wrapper
          .thirds
            label Email
            input type='email' placeholder='name@email.com' name="user[email]" id="user_email"

          .thirds
            label 
              | Password 
              small 
                | (8 or more characters)
            input type='password' placeholder='••••••' name="user[password]" id="user_password"

          .thirds
            input type="submit" class="button" value="Install Hello Bar" disabled=true

        = hidden_field_tag :detect_timezone

        .tz-brief
          | We automatically detected your timezone as <a></a>

        .tz-select
          label Timezone
          .select-wrapper
            = select 'user', 'timezone', time_zone_options

app/views/shared/modals/_confirm.html.slim
script id='confirm-modal-template' type='text/x-handlebars-template'
  .modal-wrapper
    .modal-block

      |{{#if showCloseIcon}}

      i.icon-close

      |{{/if}}

      header
        h5
          |{{title}}

      .content
        |{{text}}

      footer
        a.button.cancel href="#"
          |{{cancelBtnText}}
        form
          a.button.confirm  href="{{url}}" data-method="{{method}}" rel="nofollow"
            |{{confirmBtnText}}

app/views/shared/modals/_contact_list.html.slim
script id="contact-list-modal-template" type="text/x-handlebars-template"

  .modal-wrapper

    .modal-block#contact-list-form

      header
        h5= "{{header}}"

      .contact-list-modal

        .flash-block
          i.icon-close

        .name-and-provider-block
          form.contact_list
            label for="contact_list_name" Name
            input type="text" id="contact_list_name" name="contact_list[name]" value="My Contacts"

            label for="contact_list_provider" Where do you want your contacts stored?

            .select-wrapper
              select id="contact_list_provider" name="contact_list[provider]"
                - options_for_provider_select.each do |text, value, data|
                  = content_tag :option, text, value: value, data: data

            p
              small You can choose to keep your contacts in Hello Bar, or sync with an email service like MailChimp.
            .remote-list-select-block

        .provider-instructions-block
          / Empty

        .provider-instructions-nevermind-block
          / Empty

        .sync-details-block
          / Empty

        .hellobar-only
          p If you use an email service like MailChimp, select it from the list on the left and we'll sync your contacts there.
          p If not, no worries. We'll store your contacts in Hello Bar for now and you can change this setting later if you want.

        .loading-overlay
          .loading-message
            i.icon-settings
            | Fetching data...

      .contact-list-delete-link
        input type="hidden" id="contact_list_site_elements_count" name="contact_list[site_elements_count]" value="0"
        a.delete-confirm.hidden Delete


      footer
        a.button.cancel Cancel
        a.button.submit Done

    .modal-block#contact-list-delete
      header
        h5 Delete contact list

      .contact-list-modal

        .flash-block
          i.icon-close

        .delete-list-block
          form.delete-contact-list
            p What do you want to do with associated bars, modals, sliders and takeovers?
            .radio-wrapper
              input type="radio" id="contact_list_site_elements_action" name="contact_list[site_elements_action]" value=0 checked="checked"
              label
                | Keep associated bars, modals, sliders and takeovers
                small This will create a new, empty contact list for each
              input type="radio" id="contact_list_site_elements_action" name="contact_list[site_elements_action]" value=1
              label
                | Delete associated bars, modals, sliders and takeovers


          .confirm-delete-contact-list
            p
              | Are you sure you want to delete this contact list and all
              '  the contacts in it?
            small This will not remove any data from an email service.

      footer
        a.button.cancel Cancel
        a.button.delete Delete

/-----------  Provider Instructions Template  -----------/

script id="contact-list-modal-provider-instructions-template" type="text/x-handlebars-template"

  | <p>To integrate with {{providerName}} you'll need:</p>
  |
  | <ol>
  |   {{#if requiresEmbedCode}}
  |     <li>Your embed code from {{providerName}}</li>
  |   {{else}}
  |     {{#if requiresAccountId}}
  |       <li>The id of your account with {{providerName}}</li>
  |     {{/if}}
  |     {{#if requiresApiKey}}
  |       <li>Your API key from {{providerName}}</li>
  |     {{/if}}
  |     {{#if requiresAppUrl}}
  |       <li>Your Application Url from {{providerName}}</li>
  |     {{/if}}
  |     {{#if requiresUsername}}
  |       <li>Your {{providerName}} username and password</li>
  |     {{/if}}
  |   {{/if}}
  |   {{#unless requiresWebhookUrl}}
  |     <li>An existing list with {{providerName}} to sync to</li>
  |   {{/unless}}
  | </ol>
  |
  | <label for="contact_list_provider_info">Paste the required information below, then click Done.</label>
  |
  | {{#if requiresAppUrl}}
  |   <input type='text' class="contact_list_app_url" id="contact_list_app_url" name="contact_list[data][app_url]" value="{{contactList.data.app_url}}" placeholder="Your AppURL (eg. tx305.infusionsoft.com)">
  | {{/if}}
  |
  | {{#if requiresWebhookUrl}}
  |   <input type="url" id="contact_list_webhook_url" name="contact_list[data][webhook_url]" value="{{contactList.data.webhook_url}}" placeholder="Your webhook URL">
  |   <label for="contact_list_webhook_method">POST request
  |     <input type="checkbox" id="contact_list_webhook_method" name="contact_list[data][webhook_method]" value="{{contactList.data.webhook_method}}" {{#if webhookIsPost}}checked{{/if}}>
  |   </label>
  |   <small>Each email collected is guaranteed to be sent to the specified URL at least once, but possibly more than once. It is the responsibility of the webhook to take care of possible duplicates.</small>
  | {{/if}}
  |
  | {{#if requiresUsername}}
  |   <input type='text' class="contact_list_username" id="contact_list_username" name="contact_list[data][username]" value="{{contactList.data.username}}" placeholder="Your username">
  | {{/if}}
  |
  | {{#if requiresAccountId}}
  |     <input type='text' id="contact_list_username" name="contact_list[data][username]" value="{{contactList.data.username}}" placeholder="Your Account ID">
  | {{/if}}
  |
  | {{#if requiresApiKey}}
  |     <input type='text' class="contact_list_api_key" id="contact_list_api_key" name="contact_list[data][api_key]" value="{{contactList.data.api_key}}" placeholder="Your API key">
  | {{/if}}
  |
  | {{#if requiresEmbedCode}}
  |   <textarea class="contact_list_embed_code" id="contact_list_embed_code" name="contact_list[data][embed_code]">{{contactList.data.embed_code}}</textarea>
  | {{/if}}
  |
  | {{#unless requiresWebhookUrl}}
  |   {{#if oauth}}
  |     <div>
  |       <a class="button cancel do-this-later">I'll do this later</a>
  |       <a class="button ready">I'm ready</a>
  |     </div>
  |   {{else}}
  |     <div>
  |       <a class="button ready">Connect my account</a>
  |     </div>
  |   {{/if}}
  | {{/unless}}

/-----------  No Provider Template  -----------/

script id="contact-list-modal-provider-instructions-nevermind-template" type="text/x-handlebars-template"

  p No worries!
  p We'll store all of your contacts in Hello Bar for now.
  p Syncing with {{providerName}} can be set up any time via the contacts area, or by editing a contacts list.

/-----------  Remote List Template  -----------/

script id="contact-list-modal-remote-list-select-template" type="text/x-handlebars-template"

  | <label for="contact_list_remote_list_id">Choose a {{providerName}} list to sync with</label>
  | <div class="select-wrapper">
  |   <select id="contact_list_remote_list_id" name="contact_list[remote_list_id]">
  |     {{#each identity.lists}}
  |       <option value="{{id}}">{{name}}</option>
  |     {{/each}}
  |   </select>
  | </div>
  | {{#if identity.supports_cycle_day}}
  |   <label for="contact_list_cycle_day_enabled">
  |     <input type="checkbox" name="contact_list[cycle_day_enabled]" id="contact_list_cycle_day_enabled" value="1" {{#if cycleDayEnabled}}checked{{/if}}> Use cycle day?
  |   </label>
  |   <label for="contact_list_cycle_day_value">
  |     <input type="number" name="contact_list[cycle_day]" id="contact_list_cycle_day" value="{{cycleDay}}">
  |   </label>
  | {{/if}}
  | {{#if identity.supports_double_optin}}
  |   <label for="contact_list_double_optin">
  |     <input type="checkbox" name="contact_list[double_optin]" id="contact_list_double_optin" value="1"> Use double opt-in? (recommended)
  |   </label>
  | {{/if}}

/-----------  Sync Details  -----------/

script id="contact-list-modal-sync-details-template" type="text/x-handlebars-template"

  p Whenever a visitor to your site enters their email address into your Hello Bar, we'll automatically sync it with your {{providerName}} account.
  div
    a.button.cancel.unlink data-identity-id="{{identity.id}}" Disconnect {{providerName}}

app/views/shared/modals/_contact_list_variant.html.slim
script id="contact-list-variant-modal-template" type="text/x-handlebars-template"

  .modal-wrapper

    .modal-block#contact-list-variant-form

      header
        h5= "{{header}}"

      .contact-list-variant-modal

        .flash-block
          i.icon-close

        .name-and-provider-block
          form.contact_list
            label for="contact_list_name" What would you like to name your List?
            input type="text" id="contact_list_name" name="contact_list[name]" value="My Contacts"

            .primary-selection-block
              label After Hello Bar collects an email address, where should we send it?
              .contact-list-radio-wrapper
                - options_for_provider_select.drop(1).each do |text, value, data|
                  div class="contact-list-radio-block #{value}-provider"
                    = radio_button_tag 'contact_list[provider]', value, false, data
                    = label_tag "contact_list[provider]_#{value}" do
                      .interior-float
                        = image_tag "providers/#{value}.png"
                        span= text

                .contact-list-radio-block
                  label.show-expanded-providers
                    .interior-float
                      span View all tools

              a.small.use-hello-bar-email-lists I don't use any of these email tools

            .secondary-selection-block
              label for="contact_list_provider" Sync email subscribers
              .select-wrapper
                .select-side-icon
                select id="contact_list_provider" name="contact_list[provider]"
                  option.hidden disabled="true" Select one...
                  - options_for_provider_select.each do |text, value, data|
                    = content_tag :option, text, value: value, data: data
                .is-connected
                  i.hellobar-icon-check-mark
                  | Connected

        .provider-instructions-block
          / Empty

        .provider-instructions-nevermind-block
          / Empty

        .remote-list-select-block
          / Empty

        .sync-details-block
          / Empty

        .hellobar-only
          label After Hello Bar collects an email address, where should we send it?
          .hellobar-selection-wrapper
            .hellobar-icon
              = image_tag "providers/hellobar.png"
            small We will store your email addresses in Hello Bar. You can download the emails from the Contacts dashboard whenever you want

          i.icon-back2
          a.small.back-to-providers Nevermind, I want to view all tools

      .contact-list-delete-link
        input type="hidden" id="contact_list_site_elements_count" name="contact_list[site_elements_count]" value="0"

      footer
        a.button.cancel Cancel
        a.delete-confirm.hidden Delete this contact list
        a.button.submit Done

    .modal-block#contact-list-delete
      header
        h5 Delete contact list

      .contact-list-variant-modal

        .flash-block
          i.icon-close

        .delete-list-block
          form.delete-contact-list
            p What do you want to do with associated bars, modals, sliders and takeovers?
            .radio-wrapper
              input type="radio" id="contact_list_site_elements_action" name="contact_list[site_elements_action]" value=0 checked="checked"
              label
                | Keep associated bars, modals, sliders and takeovers
                small This will create a new, empty contact list for each
              input type="radio" id="contact_list_site_elements_action" name="contact_list[site_elements_action]" value=1
              label
                | Delete associated bars, modals, sliders and takeovers


          .confirm-delete-contact-list
            p
              | Are you sure you want to delete this contact list and all
              '  the contacts in it?
            small This will not remove any data from an email service.

      footer
        a.button.cancel Cancel
        a.button.delete Delete

/-----------  Provider Instructions Template  -----------/

script id="contact-list-variant-modal-provider-instructions-template" type="text/x-handlebars-template"

  | {{#if requiresWebhookUrl}}
  |   <label for="contact_list_username">Webhook URL</label>
  |   <input type="url" id="contact_list_webhook_url" name="contact_list[data][webhook_url]" value="{{contactList.data.webhook_url}}" placeholder="http://example.com/webhook-callback">
  |   <input type="checkbox" id="contact_list_webhook_method" name="contact_list[data][webhook_method]" value="{{contactList.data.webhook_method}}" {{#if webhookIsPost}}checked{{/if}}>
  |   <label for="contact_list_webhook_method">POST request</label>
  |   <small>Each email collected is guaranteed to be sent to the specified URL at least once, but possibly more than once. It is the responsibility of the webhook to take care of possible duplicates.</small>
  | {{/if}}
  |
  | {{#if requiresUsername}}
  |   <label for="contact_list_username">Username <small>– this can be your {{providerName}} username or email address</small></label>
  |   <input type='text' class="contact_list_username" id="contact_list_username" name="contact_list[data][username]" value="{{contactList.data.username}}" placeholder="username@example.com" />
  | {{/if}}
  |
  | {{#if requiresAccountId}}
  |   <label for="contact_list_username">{{providerName}} Account ID</label>
  |   <input type='text' id="contact_list_username" name="contact_list[data][username]" value="{{contactList.data.username}}" />
  | {{/if}}
  |
  | {{#if requiresApiKey}}
  |   {{#if requiresAppUrl}}
  |     <label for="contact_list_api_key">{{providerName}} API Key</label>
  |     <input type='text' class="contact_list_api_key_extended" id="contact_list_api_key" name="contact_list[data][api_key]" value="{{contactList.data.api_key}}" placeholder="873d71nf01n734cgh662hu" />
  |   {{else}} {{#if requiresUsername}}
  |     <label for="contact_list_api_key">{{providerName}} API Key <small>– You can find your Secret API Key within {{providerName}} > Account > API tab</small></label>
  |     <input type='text' class="contact_list_api_key_extended" id="contact_list_api_key" name="contact_list[data][api_key]" value="{{contactList.data.api_key}}" placeholder="873d71nf01n734cgh662hu" />
  |   {{else}} {{#if requiresAccountId}}
  |     <label for="contact_list_api_key">API Key</label>
  |     <input type='text' class="contact_list_api_key_extended" id="contact_list_api_key" name="contact_list[data][api_key]" value="{{contactList.data.api_key}}" />
  |   {{else}}
  |     <label for="contact_list_api_key">Enter your API key from {{providerName}}</label>
  |     <input type='text' class="contact_list_api_key" id="contact_list_api_key" name="contact_list[data][api_key]" value="{{contactList.data.api_key}}" />
  |   {{/if}}{{/if}}{{/if}}
  | {{/if}}
  |
  | {{#if requiresAppUrl}}
  |   <label for="contact_list_api_key">{{providerName}} API URL</label>
  |   <input type='text' class="contact_list_app_url" id="contact_list_app_url" name="contact_list[data][app_url]" value="{{contactList.data.app_url}}" placeholder="http://yourcompany.infusionsoft.com">
  | {{/if}}
  |
  | {{#if requiresEmbedCode}}
  |   <label for="contact_list_api_key">Enter your embed code from {{providerName}}</label>
  |   <textarea class="contact_list_embed_code" id="contact_list_embed_code" name="contact_list[data][embed_code]" placeholder="Paste your embed code here">{{contactList.data.embed_code}}</textarea>
  | {{/if}}
  |
  | {{#unless requiresWebhookUrl}}
  |   <a class="button ready">Connect</a>
  | {{/unless}}

/-----------  No Provider Template  -----------/

script id="contact-list-variant-modal-provider-instructions-nevermind-template" type="text/x-handlebars-template"

  p No worries!
  p We'll store all of your contacts in Hello Bar for now.
  p Syncing with {{providerName}} can be set up any time via the contacts area, or by editing a contacts list.

/-----------  Remote List Template  -----------/

script id="contact-list-variant-modal-remote-list-select-template" type="text/x-handlebars-template"

  | <label for="contact_list_remote_list_id">Choose a {{providerName}} list to sync with</label>
  | <div class="select-wrapper">
  |   <select id="contact_list_remote_list_id" name="contact_list[remote_list_id]">
  |     {{#each identity.lists}}
  |       <option value="{{id}}">{{name}}</option>
  |     {{/each}}
  |   </select>
  | </div>
  | {{#if identity.supports_double_optin}}
  |   <label for="contact_list_double_optin">
  |     <input type="checkbox" name="contact_list[double_optin]" id="contact_list_double_optin" value="1"> Use double opt-in? (recommended)
  |   </label>
  | {{/if}}

/-----------  Sync Details  -----------/

script id="contact-list-variant-modal-sync-details-template" type="text/x-handlebars-template"

  small After a subscriber signs up to your Hello Bar, they will be added to this list.
  div
    a.button.cancel.unlink data-identity-id="{{identity.id}}" Disconnect {{providerName}}
  small Disconnecting your {{providerName}} account will prevent Hello Bar from automattically pushing subscriptions to your list.

app/views/shared/modals/_delay_tooltip.html.erb
<script id="delay-tooltip-modal-template" type="text/x-handlebars-template">
  <div class="modal-wrapper">
    <div class="modal-block">
      <header>
        <h5>When does Hello Bar display?</h5>
      </header>

      <div class="unsaved-changes-modal">
        <p>Hello Bar lets you decide when to display your message:</p>
        <p>You can display immediately when the page loads.</p>
        <p>You can display after the visitor has been on your page for a while.</p>
        <p>You can display after the visitor scrolls.</p>
        <p>You can display just before the visitor leaves the page. Hello Bar can make a guess about the visitor's intent to exit your site, which gives you the option to deliver a 'last chance' offer or request. Hello Bar does this by watching where the cursor is and other browser data. This feature works differently on touchscreens; on mobile devices, the message will always display after 30 seconds.</p>
      </div>

      <footer>
        <a class="button cancel">Got it</a>
      </footer>
    </div>
  </div>
</script>

app/views/shared/modals/_downgrade_modal.html.slim
script id='downgrade-template' type='text/x-handlebars-template'
  - if current_site
    .modal-wrapper
      .modal-block
        header
          h5 Are you sure you want to downgrade to a free plan?

        div
        - if current_site.highest_tier_active_subscription.instance_of?(Subscription::Pro) || current_site.highest_tier_active_subscription.instance_of?(Subscription::Enterprise)
          ' You will still benefit from the #{current_site.highest_tier_active_subscription.values[:name]} plan
          ' until #{current_site.highest_tier_active_subscription.active_until.strftime("%-m-%-d-%Y")}.
          ' After that date, all of your Hello Bar elements will have the Hello Bar branding.
        - else
          ' All of your Hello Bar elements will now display Hello Bar branding.

        footer
          a.button.cancel.do-not-save Cancel
          = link_to "Downgrade", downgrade_site_path(current_site), method: :put, class: "button"

app/views/shared/modals/_exit_intent.html.slim
- if current_user.try(:can_view_exit_intent_modal?) && get_ab_variation("Exit Intent Pop-up Based on Bar Goals 2016-06-08") == "pop_up"
  - element_subtype = current_user.most_viewed_site_element_subtype
  - if element_subtype
    script id='exit-intent-modal-template' type='text/x-handlebars-template' data={ 'user-id' => current_user.id }
      .modal-wrapper
        .modal-block
          i.icon-close
          = render "shared/modals/exit_intent_content/#{element_subtype}"

app/views/shared/modals/_migration_complete.slim
script id="migration-complete-modal-template" type="text/x-handlebars-template"
  .modal-wrapper
    .modal-block
      header
        h4
          | Congratulations on upgrading!
      h5 Better analytics. Better control.
      div
        | Bars and analytics are grouped by site. Track performance, test new bars, and set up display rules, all from your new dashboard.
      h5  Find the right plan for your needs.
      div
        | We've given you a free 14-day free Pro trial for each site that you migrated, giving you better control and more bar customization options.  When your trial expires, you can choose the right plan for each site.
      h5  Add more bars—no reinstallation required!
      div
        | Create and customize bars with ease. Install your Hello Bar code once per site, then add and edit bars at will—no need to reinstall the code for each bar any more!
      footer
        a.button
          | OK

app/views/shared/modals/_multiple_choice_wrapper.html.slim
- class_name ||= false

.choice-wrapper.multiple-choice class=class_name
  | {{#if value}}
  | {{#each (toArray value)}}
  .multiple-input-wrapper
    span or

    = yield "rule[conditions_attributes][{{../index}}][value][]", "{{this}}"

    .multiple-choice-actions
      a.choice-remove –
      a.choice-add +
  | {{/each}}
  | {{else}}
  .multiple-input-wrapper
    span or

    = yield "rule[conditions_attributes][{{index}}][value][]", "{{value}}"

    .multiple-choice-actions
      a.choice-remove –
      a.choice-add +
  | {{/if}}

app/views/shared/modals/_welcome_back.html.slim
script id='welcome-back-modal-template' type='text/x-handlebars-template' data-cookie-present=cookies[:login_email]
  - if @last_logged_in_user
    .modal-wrapper
      .modal-block
        i.icon-close
        .flash-block
          i.icon-close

        header
          h5 Welcome Back!

        .avatar-block
          .user-avatar= image_tag gravatar_url_for(@last_logged_in_user), :class => 'user-avatar'
          .user-email= @last_logged_in_user.email

        .not-you= link_to 'Not you?', '#', class: 'not-last-logged-in-user'

        = simple_form_for(@last_logged_in_user, as: 'user', url: find_email_path, method: :post) do |f|
          = f.hidden_field :email

          footer
            = f.button :submit, "Log in", class: 'button'