config/routes.rb
Rails.application.routes.draw do

  #mount_ember_app :editor, to: "/editor"

  resources :referrals do
    collection do
      get :accept
    end
  end

  namespace :api do
    resources :user_state, only: :show
  end

  devise_for :users, :controllers => {:sessions => "users/sessions", :passwords => "users/passwords"}

  devise_scope :user do
    post "/users/find_email", to: "users/sessions#find_email", as: :find_email

    get "/users/forgot_email", to: "users/forgot_emails#new", as: :new_forgot_email
    post "/users/forgot_email", to: "users/forgot_emails#create", as: :forgot_email
  end

  post "/users/:user_id/update_exit_intent", to: "user_campaign#update_exit_intent", as: :update_user_exit_intent
  post "/users/:user_id/update_upgrade_suggest", to: "user_campaign#update_upgrade_suggest", as: :update_user_upgrade_suggest

  get "/auth/:action/callback", :to => "users/omniauth_callbacks", :constraints => { :action => /google_oauth2/ }

  get "profile", :to => "user#edit", :as => :profile
  resource :user, :controller => :user, :only => [:update, :destroy, :create]
  get "user/new/:invite_token", :to => "user#new", :as => :invite_user

  resources :sites do
    member do
      put :downgrade
    end

    get "team"

    post :track_selected_goal, to: "tracking#track_selected_goal"

    resource :wordpress_plugin, :controller => :wordpress_plugin

    put "site_elements/:id/toggle_paused", to: "site_elements#toggle_paused", as: :site_element_toggle_paused
    resources :site_elements
    get "site_elements/:id/edit/*path", to: "site_elements#edit"
    get "site_elements/new/*path", to: "site_elements#new"

    resources :image_uploads, only: [:create]

    resources :rules do
      resources :conditions
    end

    resources :identities
    resources :contact_lists
    resources :targeted_segments

    resources :site_memberships do
      collection do
        post "invite"
      end
    end
  end

  namespace :modals do
    get :registration
  end

  resources :payment_methods, only: [:index, :create, :update]
  resources :bills, only: :show

  get "continue_create_site", :to => "sites#create", :as => :continue_create_site
  get "sites/:id/install", :to => "sites#install", :as => :site_install
  get "sites/:id/improve", :to => "sites#improve", :as => :site_improve
  get "sites/:id/preview_script", :to => "sites#preview_script", :as => :preview_script
  get "sites/:id/script", :to => "sites#script", :as => :script
  get "sites/:id/chart_data", to: "sites#chart_data", as: :chart_data
  get "sites/:id/whats_new", :to => "sites#whats_new", :as => :whats_new

  get "/auth/:provider/callback", :to => "identities#create"

  resources :contact_submissions, only: [:create]
  get "/contact", :to => "contact_submissions#new", :as => :new_contact_submission

  %w(email_developer generic_message).each do |sub|
    post "/contact_submissions/#{sub}", :to => "contact_submissions##{sub}", :as => "#{sub}_contact_submission"
  end

  get "/admin", :to => "admin/users#index", :as => :admin
  namespace :admin do
    post "users/:id/impersonate", :to => "users#impersonate", :as => :impersonate_user
    delete "users/unimpersonate", :to => "users#unimpersonate", :as => :unimpersonate_user

    resources :admins, only: :index do
      member do
        put :unlock
      end
    end

    resources :payment_method_details, only: [] do
      put 'remove_cc_info'
    end

    resources :users, :only => [:index, :show, :destroy] do
      resources :sites, :only => [:update] do
        member do
          post :regenerate
        end

        resources :contact_lists, :only => [:index]
      end

      resources :bills, :only => [:show] do
        put 'void'
        put 'refund'
      end
    end

    get "lockdown/:email/:key/:timestamp", :to => "access#lockdown", :constraints => {:email => /[^\/]+/}, :as => :lockdown
    get "validate_access_token/:email/:key/:timestamp", :to => "access#validate_access_token", :constraints => {:email => /[^\/]+/}, :as => :validate_access_token
    get "logout", :to => "access#logout_admin", :as => :logout
    get "reset_password", :to => "access#reset_password"
    post "reset_password", :to => "access#do_reset_password"
    get "access", :to => "access#step1", :as => :access
    post "access/authenticate", :to => "access#process_step2", :as => :authenticate
    post "access", :to => "access#process_step1"
    get "locked", :to => "access#locked", :as => :locked
  end

  post "/track/current_person/did/:event" => "tracking#track_current_person"
  post "/track/:type/:id/did/:event" => "tracking#track"
  get "/pixel.gif" => "tracking#pixel", :as => :tracking_pixel

  get "/install" => "sites#install_redirect"

  get '/use-cases' => 'pages#use_cases'
  get '/amazon' => 'pages#use_cases'
  get '/terms-of-use' => 'pages#terms_of_use'
  get '/privacy-policy' => 'pages#privacy_policy'
  get '/migrate-faq' => 'pages#migrate_faq'
  get '/logged_out' => 'pages#logout_confirmation', as: :logout_confirmation

  get "/heartbeat" => "heartbeat#index"
  get "/login", to: redirect("/users/sign_in")
  get "/signup", to: redirect("/")

  get "/user_migration", to: "user_migration#new", as: :new_user_migration
  get "/upgrade", to: "user_migration#upgrade", as: :user_migration_landing
  post "/start_migration", to: "user_migration#start", as: :start_user_migration
  post "/user_migration", to: "user_migration#create", as: :user_migration

  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  get "/proxy/:scheme/*url", to: "proxy#proxy" if Rails.env.development?

  get "/email-signup", to: "welcome#email_quickstart"
  root "welcome#index"
end

app/views/shared/_alert_template.slim
script id="alert-template" type="text/x-handlebars-template"
  div class="alert {{type}}"
    | {{{content}}}

app/views/shared/_contact_list_modal.html.slim
script id="contact-list-modal-template" type="text/x-handlebars-template"
  .modal-wrapper.contact-list-modal
    .modal-block
      h4= "{{header}}"
      hr

      .provider-instructions-block
      .provider-instructions-nevermind-block
      .name-and-provider-block
        form.contact_list
          label for="contact_list_name" Name
          input type="text" id="contact_list_name" name="contact_list[name]"

          label for="contact_list_provider" Where do you want your contacts stored?
          select id="contact_list_provider" name="contact_list[provider]"
            = options_for_provider_select.each do |option|
              option value="#{option[1]}"
                = option[0]

          p
            small You can choose to keep your contacts in Hello Bar, or sync with an email service like MailChimp.
          .remote-list-select-block

      hr
      a.button.submit Done
      a.button.cancel Cancel

script id="contact-list-modal-provider-instructions-template" type="text/x-handlebars-template"
  p To integrate with {{providerName}} you'll need:

  ol
    li Your {{providerName}} username and password
    li To have an existing list with {{providerName}} to sync to

  p
    a.do-this-later I'll do this later
    a.start-oauth.button I'm ready

script id="contact-list-modal-provider-instructions-nevermind-template" type="text/x-handlebars-template"
  p No worries!
  p We'll store all of your contacts in Hello Bar for now.
  p Syncing with {{providerName}} can be set up any time via the contacts area, or by editing a contacts list.

script id="contact-list-modal-remote-list-select-template" type="text/x-handlebars-template"
  | <label for="contact_list_remote_list_id">Choose a {{providerName}} list to sync with</label>
  | <select id="contact_list_remote_list_id" name="contact_list[remote_list_id]">
  |   {{#each identity.lists}}
  |     <option value="{{id}}">{{name}}</option>
  |   {{/each}}
  | </select>
  | {{#if identity.supports_double_optin}}
  |   <label for="contact_list_double_optin">
  |     <input type="checkbox" name="contact_list[double_optin]" id="contact_list_double_optin" value="1"> Use double opt-in? (recommended)
  |   </label>
  | {{/if}}

app/views/shared/_flash.html.slim
- flash.each do |key, message|
  - next unless message.present?
  .flash-block class=key
    i.icon-close
    - if message.is_a?(Array)
      - message.each do |msg|
        div= sanitize(msg, attributes: %w{ href target style })
    - else
      = sanitize(message, attributes: %w{ href target style })

app/views/shared/_footer.html.slim
= active_link_to 'Sign In', new_user_session_path
= active_link_to 'Use Cases', use_cases_path
= active_link_to 'Terms of Use', terms_of_use_path
= active_link_to 'Privacy Policy', privacy_policy_path
= active_link_to 'Help', Hellobar::Settings[:support_location]

span.copyright
  | &copy; Hello Bar&nbsp;
  = Time.current.year

app/views/shared/_header.html.slim
.header-logo-block
  - if current_user && current_site
    = link_to(site_path(current_site)) do
      = image_tag("hellobar_logo_white.svg")
  - else
    = link_to(root_path) do
      = image_tag("hellobar_logo_white.svg")

- if current_user && current_site
  .header-nav-wrapper
    .dropdown-wrapper.no-hover#site-selector
      div.site-label SITE
      span.site-name= current_site.normalized_url
      span.caret
        = image_tag('caret-down.svg')
      .dropdown-block
        = active_link_to 'Site Settings', (current_user ? edit_site_path(current_site) : root_path)
        - if current_site.is_free?
          = content_tag 'a', 'Hello Bar PRO', class: "show-upgrade-modal", data: { source: 'Hello Bar PRO' }
        h6= current_user.sites.count <= 1 ? "Sites" : "Switch Sites"
        ul
          - current_user.sites.sort_by(&:normalized_url).each do |site|
            li.padded
              =active_link_to site.normalized_url, site_path(site)
              - unless site.is_free?
                div.pill class=site.current_subscription.values[:name]
                  = site.current_subscription.values[:name][0..2]
        = button_to "Add New Site", new_site_path, :class => "button", :method => :get

  .header-user-wrapper
    .ctas
      - unless current_user.temporary?
        - if current_site.is_free?
          a.button.show-upgrade-modal data={ source: "Menu Button: Want More Power" }
            | Want More Power?

        - elsif current_site.current_subscription.try(:currently_on_trial?)
          a.button.show-payment-modal data={ source: "Add payment to trial" }
            div Enjoying Hello Bar Pro?

    .dropdown-wrapper.no-hover
      = image_tag gravatar_url_for(current_user), :class => 'user-avatar'
      span.user-name= display_name_for_user(current_user)
      span.caret
        = image_tag('caret-down.svg')
      .dropdown-block
        = active_link_to 'User Settings', profile_path()
        - if current_site.is_free?
          = content_tag 'a', 'Upgrade Plan', class: "show-upgrade-modal", data: { source: "Header Drop-down" }
        - else
          = content_tag 'a', 'Payment Info', class: "show-payment-modal"
        - if impersonated_user
          = active_link_to "Stop Impersonating", admin_unimpersonate_user_path, :method => :delete
        - else
          = active_link_to 'Sign Out', destroy_user_session_path, :method => :delete
- elsif current_user
  .header-user-wrapper
    .ctas
      a.button.show-upgrade-modal data={ source: "Menu Button: Want More Power" }
      | Want more power?
    .dropdown-wrapper
      = image_tag gravatar_url_for(current_user), :class => 'user-avatar'
      span.user-name= display_name_for_user(current_user)
      span.caret
        = image_tag('caret-down.svg')
      .dropdown-block
        = active_link_to 'Sign Out', destroy_user_session_path, :method => :delete

app/views/shared/_hellobar_script.html.slim
- unless Rails.env.test?
  script src="//my.hellobar.com/be9aebb2c965e0e698c67b101deb1c135c231977.js" type="text/javascript" charset="utf-8" async="async"

app/views/shared/_hotjar.html.slim
javascript:
  (function(h,o,t,j,a,r){ h.hj=h.hj||function() {(h.hj.q=h.hj.q||[]).push(arguments)} ; h._hjSettings= {hjid:319095,hjsv:5} ; a=o.getElementsByTagName('head')[0]; r=o.createElement('script');r.async=1; r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv; a.appendChild(r); })(window,document,'//static.hotjar.com/c/hotjar-','.js?sv='); 

app/views/shared/_optimizely.html.slim
script src="//cdn.optimizely.com/js/992291935.js"

app/views/shared/_payment_issue_prompt.html.slim
.prompt.payment-issue-prompt
  span= "You have an outstanding bill for #{number_to_currency(payment_issue_amount(site))}, dated #{payment_issue_date(site).strftime("%b %d, %Y")}. #{link_to "Fix this", edit_site_path(site)}.".html_safe

app/views/shared/_prompt.html.slim
- if site_has_payment_issue?(@site)
  = render "shared/payment_issue_prompt", {site: @site}
- elsif show_whats_new_prompt?
  = render "shared/whats_new_prompt", {site: @site}

app/views/shared/_rule_modal.html.slim
.modal-wrapper

  .modal-block

    header
      h5= rule.persisted? ? 'Edit Rule' : 'New Rule'

    = simple_form_for [site, rule], defaults: { label: false }, html: {class: 'form-inline rule-modal', id: "rule-#{rule.id}"} do |rule_form|

      p
        | Show
        span= rule_form.number_field :priority, min: 1, max: 100, step: 1
        | % of people who match
        span.select-wrapper
          = rule_form.select :match, Rule::MATCH_ON, include_blank: false
        | of the following conditions.

      .conditions-wrapper
        = rule_form.fields_for :conditions do |condition_form|
          .condition-block
            .condition-ruleset
              .select-wrapper.optional.rule_conditions_segment
                = condition_form.select :segment, Condition::SEGMENTS.invert, { include_blank: false }, { class: 'condition-segment' }

              .select-wrapper.optional.rule_conditions_operand
                = condition_form.select :operand, Condition::OPERANDS.invert, { include_blank: false }, { class: 'condition-operand' }

              .rule_conditions_choices

                .choice-wrapper.date-choice
                  = ConditionInputHelper.start_date_field(condition_form)
                  = ConditionInputHelper.end_date_field(condition_form)

                .choice-wrapper.url-choice
                  = ConditionInputHelper.url_field(condition_form)

                .choice-wrapper.select-wrapper.country-choice
                  = ConditionInputHelper.country_field(condition_form)

                .choice-wrapper.select-wrapper.device-choice
                  = ConditionInputHelper.device_field(condition_form)

              = condition_form.hidden_field :_destroy, class: 'destroy'

            .condition-actions
              = link_to raw("&#45;"), '#', class: 'condition-remove'
              = link_to raw('&#43;'), '#', class: 'condition-add'

        .condition-block.no-condition-message
          .condition-ruleset
            small
              | There are no conditions yet, so this rule matches 
              strong everyone. 
              br
              | To only match certain people click the blue (+) button to the right.

          .condition-actions
            = link_to raw('&#43;'), '#', class: 'condition-add'

      = rule_form.label :name
      = rule_form.text_field :name

      footer
        = link_to 'Cancel', '#', class: 'cancel button'
        = button_tag 'Save', class: 'button'

/-----------  JS Templates  -----------/

script type="text/template" id="new-condition"
  .placeholder
    .condition-block
      .condition-ruleset
        .select-wrapper.optional.rule_conditions_segment
          = select_tag :segment, options_for_select(Condition::SEGMENTS.invert), class: 'condition-segment'

        .select-wrapper.optional.rule_conditions_operand
          = select_tag :operand, options_for_select(Condition::OPERANDS.invert), class: 'condition-operand'

        .rule_conditions_choices
          .choice-wrapper.date-choice
            = date_field_tag :value, nil, class: 'start_date value', disabled: true
            = date_field_tag :value, nil, class: 'end_date value', disabled: true

          .choice-wrapper.url-choice
            = text_field_tag :value, nil, class: 'url value', disabled: true, :placeholder => 'something...'

          .choice-wrapper.select-wrapper.country-choice
            = select_tag :value, options_for_select(['USA', 'USA', 'USA']), include_blank: false, class: 'country value', disabled: true

          .choice-wrapper.select-wrapper.device-choice
            = select_tag :value, options_for_select(['Desktop', 'Mobile']), include_blank: false, class: 'device value', disabled: true

      .condition-actions
        = link_to raw("&#45;"), '#', class: 'condition-remove'
        = link_to raw('&#43;'), '#', class: 'condition-add'

app/views/shared/_sidebar.html.slim
- if current_site
  ul
    li
      = active_link_to site_path(current_site), :active => :exclusive do
        i.icon-summary
        | Summary
    li
      = active_link_to site_site_elements_path(current_site) do
        i.icon-manage
        | Manage
    - if current_site.has_script_installed?
      li
        = active_link_to site_improve_path(current_site) do
          i.icon-growthbars
          | Analyze
    li
      = active_link_to site_contact_lists_path(current_site) do
        i.icon-contacts
        | Contacts
    li
      = active_link_to edit_site_path(current_site) do
        i.icon-settings
        | Settings
    li
      = active_link_to new_referral_path() do
        i.icon-tip
        | Get Free Pro
    li
      = link_to(Hellobar::Settings[:support_location], target: '_blank') do
        i.icon-support
        | Help

  = button_to "Create New", new_site_site_element_path(:site_id => current_site), :class => "button", :method => :get, "data-prompt-upgrade" => current_site.capabilities.at_site_element_limit?, "data-upgrade-benefit" => "create more bars"

app/views/shared/_update_for_old_users.html.slim
- if current_user && current_user.wordpress_user_id.present? && current_user.created_at > 7.days.ago
  table#old-user-update style="margin-top:0px; #{'display:none;' if cookies['dismissUserUpdate'] == 'true'}"
    tr
      td.color-flag style="background-color: rgb(232,86,42);"
      td= "<b>Where did all my views and conversions go?</b></br>When we imported your bars from Hello Bar 1.0 we weren't able to copy over your history of views and conversions. However, you'll start tracking new views and conversions as normal.".html_safe
      td
        a.button style="width:74px;" href="#" id="hide-btn-old-user-update" Got it

app/views/shared/_whats_new_prompt.html.slim
.prompt.whats-new-prompt
  span= link_to "Click here to see what's new in Hello Bar", whats_new_path(site)